device: "/dev/tty.usbmodem1432402"
#device: "/dev/tty.usbmodem1432202"
#device: "/dev/tty.usbmodem1432201"
#device: "/dev/tty.usbmodem14101"
baudrate: 115200
discovery_topic: "homeassistant"
thermometers: []

binary_sensors:
  - name: "Détecteur de débit TEST"
    pin: 11
    device_class: "running"
relays:
  - name: "Test Relay 1"
    pin: 8
    type: "NC"
  - name: "Test Relay 2"
    pin: 7
    type: "NO"
  - name: "Test Relay 3"
    pin: 6
    type: "NC"
    device_class: "switch"
    domain: "light"
  - name: "Test Relay 4"
    pin: 5
    type: "NO"
    device_class: "switch"
  - name: "Thermometers AUTO ON/OFF (TEST)"
    pin: 13
    type: "NC"
    device_class: "switch"
calibrations:
  - name: joypad
    x_point: 103
    y_point: 0.2
  - name: joypad
    x_point: 151
    y_point: 0.8
sensors:
  - name: "JoypadX"
    pin: "A0"
    #threshold: 3
    freq: 100
    unit: bar
    device_class: pressure
    calibration_points_name: joypad
  - name: "JoypadY"
    pin: "A1"
    #threshold: 3
    freq: 100
    unit: bar
    device_class: pressure
#thermometers:
#  - name: "Thermometers AUTO TEST"
#    pin: 12
#    controler: AUTO-DS18B20
